import { createSlice } from "@reduxjs/toolkit";

// Initial state for the user slice
const initialState = {
	currentUser: null,
	isLoggedIn: false,
};

// Create a slice for user state management
const userSlice = createSlice({
	name: "user",
	initialState,
	reducers: {
		setCurrentUser: (state, action) => {
			state.currentUser = action.payload;
			state.isLoggedIn = true;
		},
		// logoutUser: (state) => {
		// 	state.currentUser = null;
		// 	state.isLoggedIn = false;
		// },
	},
});

// Export actions generated by createSlice
export const { setCurrentUser } = userSlice.actions;

// Export the reducer
export default userSlice.reducer;
